### ISSUE TITLE
Can I add your project to the examples section on LyricsGenius?

### ISSUE THREAD

**Issue by johnwmillr** [Hugo-Nattagh/2017-Hip-Hop#1]
Hey Hugo, nice project! Do you mind if I add a link to your repo in the [examples section](https://github.com/johnwmillr/LyricsGenius#example-projects) of LyricsGenius?

John

**Comment by Hugo-Nattagh** [comment]
Oh woah hey John!
I'm so sorry that I'm seeing this only now!
Thank you and yes of course you can :)

**Comment by johnwmillr** [comment]
Great! I've updated the [README](https://github.com/johnwmillr/LyricsGenius#example-projects).

Cheers!
